### ISSUE TITLE
Release and tag 2.1.2

### ISSUE THREAD

**Issue by cimasim89** [cimasim89/flat-file-creator#35]

**Comment by kael-shipman** [comment]
Was just going to ask about this! Is there anything blocking the release?

**Comment by cimasim89** [comment]
Hi Kael, the main problem is time. I have changed default branch from master to v2.x, now I have to merge develop into it right? after that, we need a release branch where we will tag release?

**Comment by kael-shipman** [comment]
Yes, from here all we have to do is merge `develop` into `v2.x`. If you'd like to be able to issue patch releases on the `v2.1.x` branch, then we should make a `v2.1.x` branch (which would be the "release branch" in this case) also, but it's not strictly necessary. I had mentioned that in my proposal because that's how I manage bigger projects with more dependents so that if I need to issue patch releases, I can go back and issue the patch release for each minor release in the suite. Again, though, for something like this, I'd be just as happy to leave it at `v2.x`.

Either way, though, my opinion is that once we've merged `develop`, that branch should be deleted in favor of using the primary version branch as the tip of development.

**Comment by cimasim89** [comment]
yes, after merge `develop` into `v2.x`, `develop` won't be used anymore and we'll merge PR directly into `v2.x`, my doubt is this, will we tag releases directly on `v2.x` or/and on any descendants (e.g. `v2.1.x`)?

**Comment by kael-shipman** [comment]
I think it depends on how granular we want to be. I'd say with this project, we just use a `v2.x` branch and NOT a `v2.1.x` branch, and then the question is self-resolving because there's only one branch, `v2.x`. If the project were to grow significantly (which seems doubtful, given the scope), then we may want to start using minor-version branches (e.g., `v2.1.x`) and then we would probably tag on those.

The idea is just that we have a development tip for each supported branch of development. For example, if we're on version 3.5, but a bad bug is discovered in version 1.3.2,  we can go back to the `v1.x` branch, commit the fix, tag release `v1.3.3`, then merge that forward to the `2.x` branch and then the `3.x` branch.

In that case, it would be just as easy to check out the tag `v1.3.2` and create a hotfix branch from it, but in my opinion it's nice to have the easy references, and it also helps show others exactly where development has branched off and where we're at now.

**Comment by kael-shipman** [comment]
@cimasim89 sorry to keep bothering you about this, but all I need in order to be done with this is the updated v2.1.1 package published on npmjs.com. Lemme know if I can help.

**Comment by cimasim89** [comment]
Hi Kael, maybe I posed my question in a wrong way, I don't understand if the right place for the new Release Tag is the branch `v2.x` that is the same place where we merge all the new features, or will we use another branch?
Anyway I will resolve soon the conflict on merging `develop` into `v2.x` that seems to have some conflicts.

**Comment by kael-shipman** [comment]
Yes, my opinion is that we a) merge all of our changes into `v2.x` branch, then b) tag branch `v2.x` with release tag `v2.1.1`.

**Comment by cimasim89** [comment]
Hi @kael-shipman I changed version target to v2.1.2, I had updated some dependencies and resolved conflicts founded on merging `develop` into `v2.x`.
Can you test and approve PR #62 ?
